### ISSUE TITLE
Structure plot of iPSC by batch, individual, cell cycle

### ISSUE THREAD

**Issue by jhsiao999** [jhsiao999/singleCell-method#5]
Hey Kushal,

Can you rerun this code and save the admixture output in an rda file? Please put it under project/rdas/cell_phase_analysis.rda.

The admixture took too long to run on my computer, and we should not have to re-run admixture every time this script is run. Also, please look at my batch effect htmls for examples of adding table of content and headings and also notes to the code chunks. These seem annoying details, but we need the code to be easily accessible by anyone (besides the two of us).... Thank you so much!

Joyce

**Comment by kkdey** [comment]
Okay....I will save the files as rda to the output folder then...and I should do that for LCL and iPSC+LCL analysis right?

**Comment by jhsiao999** [comment]
We are gonna have to do this for all of the htmls you did. Please do for LCL after tomorrow. I am staring at them now...

**Comment by kkdey** [comment]
All the rda files are in project/rdas and the scripts are in project/analysis and graphs in project/figures
