### ISSUE TITLE
Write down the batch effects correction model

### ISSUE THREAD

**Issue by kkdey** [jhsiao999/singleCell-method#7]

**Comment by kkdey** [comment]
The batch correction scheme as of now is here: https://github.com/jhsiao999/singleCell-method/blob/master/project/docs/batch_effect_correct.pdf

**Comment by jhsiao999** [comment]
Just to make sure. This is the scheme, but we haven't fitted a model with the sum constraint, right? 

Also, let's think about if we should do CPM correction on the counts before correcting for batch effect.

**Comment by kkdey** [comment]
I have already incorporated the sum constraint....the CPM correction does not quite change the batch correction scheme..the reason is if we fit the model on the CPM, then the \alpha_g will automatically get adjusted...and when we take the exponent of the fitted model, we have to incorporate the adjustment again, which will give us the same result as log (c_{ng}).....anyways topic model in itself intrinsically uses the CPM..so I think CPM normalization will probably not make much of a difference

**Comment by jhsiao999** [comment]
Hmm. RNA-seq data is known to be overdispersed, so by using the exponential of the log transformed data as the poisson parameter, we are assuming that the corrected data is not overdispersed anymore? What do you think?

**Comment by kkdey** [comment]
Thats a good point... however I still think there is some overdispersion...Note that the \hat{\alpha_g} and  r_{ng} or the residuals are not fixed values but are random variables following some Normal distribution as per the linear model we are fitting....So overdispersion will still crop up due to the randomness in $r_{ng}$....The model is Poisson given these random variables...but in terms of loglikelihood, we also need to take into account the normal distribution of these random fitted values

**Comment by jhsiao999** [comment]
Closing this issue for now. We have shifted our focus away from batch effect correction.
